name: Build and test

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  flutter_test:
    runs-on: macOS-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install and start simulator
        uses: futureware-tech/simulator-action@v4
        with:
          model: 'iPhone 16'

      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: install dependencies
        run: flutter pub get

      - name: run unit tests
        run: flutter test test/unit

      - name: run integration tests
        run: flutter test integration_test
